# Config Mosquitto pour le projet lentIA
# Listener MQTT classique (pour le Pico W, le client de test, l'API...)
listener 1883
allow_anonymous true

# Listener WebSocket (pour que le dashboard web s'abonne en direct depuis le navigateur)
listener 9001
protocol websockets
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
